twist_mux:
  ros__parameters:

    use_stamped: true

    topics:
      keyboard:
        topic   : cmd_vel_keyboard
        timeout : 0.5
        priority: 90
      navigation:
        topic   : cmd_vel
        timeout : 0.5
        priority: 10
      joystick:
        topic   :  teleop_vel
        timeout : 0.5
        priority: 100